---
# ClickHouse Keeper Cluster
apiVersion: "clickhouse-keeper.altinity.com/v1"
kind: "ClickHouseKeeperInstallation"
metadata:
  name: {{ .Values.config.chk.name }}
  namespace: {{ .Values.namespace }}
spec:
  configuration:
    clusters:
      - name: {{ .Values.config.chk.name }}
        layout:
          replicasCount: {{ .Values.config.chk.resources.replicasCount | default 3 }}
    settings:
      logger/level: "information"
      logger/console: "true"
      listen_host: "0.0.0.0"
      keeper_server/four_letter_word_white_list: "*"
      keeper_server/coordination_settings/raft_logs_level: "information"
{{- if .Values.config.chk.monitoring.enabled }}
      prometheus/endpoint: "/metrics"
      prometheus/port: "7000"
      prometheus/metrics: "true"
      prometheus/events: "true"
      prometheus/asynchronous_metrics: "true"
      prometheus/status_info: "false"
{{- end }}
  defaults:
    templates:
      podTemplate: default
      dataVolumeClaimTemplate: default

  templates:
    podTemplates:
      - name: default
{{- if .Values.config.chk.monitoring.enabled }}
        metadata:
          annotations:
            prometheus.io/port: "7000"
            prometheus.io/scrape: "true"
{{- end }}
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: "app"
                        operator: In
                        values:
                          - clickhouse-keeper
                  topologyKey: "kubernetes.io/hostname"
          containers:
            - name: clickhouse-keeper
              imagePullPolicy: IfNotPresent
              image: "clickhouse/clickhouse-keeper:{{ .Values.config.clickhouse_version }}"
              resources:
                requests:
                  memory: "{{ .Values.config.chk.resources.requests.memory }}"
                  cpu: "{{ .Values.config.chk.resources.requests.cpu}}"
                limits:
                  memory: "{{ .Values.config.chk.resources.limits.memory }}"
                  cpu: "{{ .Values.config.chk.resources.limits.cpu}}"
          securityContext:
            fsGroup: 101

    volumeClaimTemplates:
      - name: default
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ .Values.config.chk.resources.disk_volume_size |default "10Gi" }}
