apiVersion: v2
name: clickhouse
description: Clickhouse Cluster Configuration. This assumes a the affinity CH operator (https://docs.altinity.com/clickhouse-operator/ ) has already been installed.
version: 0.0.4
maintainers:
  - name: esnet
    email: "esnet-seg-ma@lbl.gov"
